name: upper-cross

on:
  push:
    paths:
        - ".github/workflows/upper-cross.yml"
        - "upper/**"
  workflow_dispatch: # manual

jobs:
  cross:
    permissions:
      contents: write
    # strategy:
      # matrix:
        # os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: upper
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22
          cache-dependency-path: ./upper/go.sum
      - run: ls
      - run: ./build.xplat.sh
      - uses: softprops/action-gh-release@v2
        with:
          files: ./upper/bin/upper*
          body: "Binaries for the upp (g0) command!!!"
          tag_name: ${{ github.ref_name }}
      # - uses: actions/upload-artifact@v4
      #   with:
      #     path: ./upper/bin/upper*
      #     name: build

