name: upper-build

on:
  push:
    paths:
      - ".github/workflows/upper-biild"
      - "upper/**"
  workflow_dispatch: # manual

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: go version


